---
- name: Deploy server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      tags: deploy
    # - swarm_init
- name: Rest
  hosts: rest
  roles:
    - role: preconfig
      tags: preconfig
    # - swarm_join
