galaxy_info:
  role_name: swarm_init
  description: Инициализация swarm кластера
  author: Viktor Kopan
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
