---
- name: Docker install
  become: true
  block:
    - name: Adding ubuntu universe repository
      ansible.builtin.apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Install additional packages
      ansible.builtin.apt:
        cache_valid_time: 86400
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        update_cache: true

    - name: Add Docker official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyrings.gpg

    - name: Set up docker repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyrings.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update_cache: true

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true

    - name: Check Docker install and restart
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true
- name: "Установка доп пакетов python"
  block:
    - name: Установка pip пакетов
      ansible.builtin.pip:
        name: docker

- name: Finish
  become: true
  block:
    - name: Adding user to Docker user group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups:
          - docker
        append: true

    - name: Rebooting
      ansible.builtin.reboot:
